### ISSUE TITLE
Supertypes of the following classes cannot be resolved

### ISSUE THREAD

**Issue by all2pie** [Mapwize/mapwize-ui-android#29]
Getting the following error:

Supertypes of the following classes cannot be resolved.
Please make sure you have the required dependencies in the classpath:
  class io.mapwize.mapwizeui.SearchDirectionView, unresolved supertypes:
    io.mapwize.mapwizesdk.map.MapwizeMap.OnDirectionModesChangeListener

My Gradle Build File (App):

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.example.indoorlocationtracking"
        minSdkVersion 26
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.core:core-ktx:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation "com.github.Mapwize:mapwize-ui-android:2.2.0"
    implementation 'com.github.indoorlocation:manual-indoor-location-provider-android:1.0.0'
    implementation 'io.mapwize.sdk:mapwize-sdk:3.1.11'

}

repositories {
    mavenCentral()
}

```

My Gradle Build File (Project):

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.71'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.mapwize.io'}
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by emerciercontexeo** [comment]
Hi, 

Thanks for reporting this issue, I will check it and will come back to you as soon as possible

Etienne

**Comment by emerciercontexeo** [comment]
Hi again,

It is possible that it come from the missing compatibility in your gradle file

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

Let me know,

Etienne

**Comment by emerciercontexeo** [comment]
Hi,

The MapwizeSDK version that you are using is not compatible with the UI version.

You should use SDK 3.2.x which contains DirectionMode and DirectionModeListener.

Sorry for missing this point in the first place.

Please take a look at this repo, there is an example of MapwizeUI integration.

https://github.com/Mapwize/mapwize-examples-android

Etienne

**Comment by all2pie** [comment]
Thanks, Fixed that but now getting this error: 

```
android.view.InflateException: Binary XML file line #28 in com.example.indoorlocationtracking:layout/mapwize_fragment: Binary XML file line #28 in com.example.indoorlocationtracking:layout/mapwize_fragment: Error inflating class io.mapwize.mapwizeui.SearchBarView
    Caused by: android.view.InflateException: Binary XML file line #28 in com.example.indoorlocationtracking:layout/mapwize_fragment: Error inflating class io.mapwize.mapwizeui.SearchBarView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
```

sorry to bother.

**Comment by emerciercontexeo** [comment]
Hi,

Sorry for the delay.

Did you set a MapwizeConfiguration somewhere in your application?

Something like MapwizeConfiguration.start(new MapwizeConfiguration.Builder("YOUR_API_KEY").build())

Etienne

**Comment by all2pie** [comment]
I think that might be the issue

I shifted to indoor Atlas as i needed some free service and was having issues with the admin panel
